apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-sul
  namespace: saevecke
  labels:
    app: coffee-sul
spec:
  selector:
    matchLabels:
      app: coffee-sul
  replicas: 12
  template:
    metadata:
      labels:
        app: coffee-sul
      annotations:
        kube-remediator/CrashLoopBackOffRemediator: "true"
    spec:
      containers:
      - name: coffee-sul
        image: pixian/sul:coffee-spring-native-graalvm
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: ENABLE_SYMBOL_DELAY
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: symbol_delay_enabled
          - name: MAX_DELAY_PER_SYMBOL_MS
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: max_delay_per_symbol_ms
          - name: MIN_DELAY_PER_SYMBOL_MS
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: min_delay_per_symbol_ms
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: SPRING_RABBITMQ_HOST
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: rabbitmq_host
          - name: SPRING_RABBITMQ_PORT
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: rabbitmq_port
          - name: SPRING_RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: RABBIT_USERNAME
          - name: SPRING_RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: RABBIT_PASSWORD