apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret
  namespace: saevecke
data:
  host: "YW1xcDovL2d1ZXN0Omd1ZXN0QG11LXJhYmJpdC1yYWJiaXRtcS5zYWV2ZWNrZS5zdmMuY2x1c3Rlci5sb2NhbDo1NjcyL3Zob3N0"
  # cluster: YW1xcDovL2d1ZXN0Omd1ZXN0QG11LXJhYmJpdC1yYWJiaXRtcS5zYWV2ZWNrZS5zdmMuY2x1c3Rlci5sb2NhbDo1NjcyL3Zob3N0
  # local: YW1xcDovL2d1ZXN0Omd1ZXN0QG11LXJhYmJpdC1yYWJiaXRtcS5yYWJiaXQuc3ZjLmNsdXN0ZXIubG9jYWw6NTY3Mi92aG9zdA==
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-rabbitmq-conn
  namespace: saevecke
spec:
  secretTargetRef:
  - parameter: host
    name: keda-rabbitmq-secret
    key: host
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-scaledobject
  namespace: saevecke
  labels:
    deploymentName: sul
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sul
  pollingInterval: 1  # Optional. Default: 30 seconds
  cooldownPeriod:  6000
  minReplicaCount: 0
  advanced:
    horizontalPodAutoscalerConfig: # Optional. Section to specify HPA related options
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
            - type: Percent
              value: 100
              periodSeconds: 30
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Percent
              value: 100
              periodSeconds: 10
            - type: Pods
              value: 4
              periodSeconds: 30
          selectPolicy: Max
  triggers:
  - type: rabbitmq
    metadata:
      protocol: amqp
      mode: QueueLength # QueueLength or MessageRate
      queueName: sul_input_q
      value: "1"
      vhostName: /
    authenticationRef:
      name: keda-trigger-auth-rabbitmq-conn