
apiVersion: 1
providers:
  - name: 'default'
    orgId: 1
    folder: 'default'
    type: file
    disableDeletion: true
    editable: true
    options:
      path: /var/lib/grafana/dashboards/standard
dashboards:
  default:
    imported-dashboard-name:
      gnetId: 10991
      datasource: prometheus