## Prometheus Metrics
metrics:
  enabled: true
  plugins: 'rabbitmq_prometheus'
  podAnnotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '{{ .Values.service.metricsPort }}'

  ## Prometheus Service Monitor
  ## ref: https://github.com/coreos/prometheus-operator
  serviceMonitor:
    enabled: true
    interval: 30s
    additionalLabels:
      monitoring-platform: core-prometheus